#!/usr/bin/env ruby

require File.expand_path('../../config/environment',  __FILE__)
require File.expand_path('../../test/support/sample_data', __FILE__)

cr = CertificateRequest.new(SampleData::AUTOMATIC_CERTIFICATE_REQUEST_WITH_TIMESTAMPS)
File.open('demo.pdf', 'w') do |f|
  f.write(CertificateBuilder.build(cr))
end
